name: Deployment

on:
    push:
        branches:
        - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout
              uses: actions/checkout@v2
    
            - name: Use Node 18
              uses: actions/setup-node@v1
              with:
                node-version: 18.x

            - name: Install Dependencies
              run: npm install
  
            - name: Run tests
              run: npm run test:integration
                   npm run test:component